apiVersion: apps/v1
kind: Deployment
metadata:
  name: quote-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quote-db
  template:
    metadata:
      labels:
        app: quote-db
    spec:
      containers:
        - name: quote-db
          image: postgres:17
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
            - name: POSTGRES_DB
              value: "postgres"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
            - name: init-sql
              mountPath: /docker-entrypoint-initdb.d/
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "postgres"]
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: pgdata-pvc
        - name: init-sql
          configMap:
            name: init-sql
